# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ☢️ Breaking changes
    labels:
      - "☢️ breaking change"
  - title: 🎉 Notable changes
    labels:
      - "notable changes"
  - title: 🚀 New features and improvements
    labels:
      - enhancement
  - title: 🐛 Bug fixes
    labels:
      - bug
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: 👻 Maintenance
    labels:
      - chore
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
  - title: ✍ Other changes
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 5
  - title: 🔐 Security
    labels:
      - "🔐 security"
exclude-labels:
  - skip-changelog
  - invalid

template: |
  $CHANGES

  ## Sponsors

  We would like to thank our sponsors for their support during this release.

  > [!CAUTION]
  > Please make sure that all the current sponsors (from our README) are added here.
  >
  > Please also note that the URLs will need pinning to the release we're about to publish.

  i.e.

  <p align="center">
    <a href="https://elastic.co?utm_source=oapi-codegen+repo&utm_medium=github+sponsorship">
      <picture>
      .github/sponsors/devzero-dark.svg
        <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.4.0/.github/sponsors/elastic-light.svg">
        <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.4.0/.github/sponsors/elastic-dark.svg">
        <img alt="Elastic logo" src="https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.4.0/.github/sponsors/elastic-dark.svg" height="100px">
      </picture>
    </a>
  </p>

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
